### ISSUE TITLE
Safari style bug - :focus is applied on the body 

### ISSUE THREAD

**Issue by yassinrais** [mattcroat/joy-of-code#99]
You should not apply the `focus` on all elements, in safari the `focus` is applied on `body` tag

```css
*:focus { outline: 3px solid blue }
```
⬇️ 
```css
body *:focus { outline: 3px solid blue }
```
<img width="912" alt="Screenshot 2022-12-09 at 15 31 33" src="https://user-images.githubusercontent.com/25354731/206724927-dc4476b5-9084-4772-a113-acd8b732f388.png">
